name: CI

on:
  push:
    branches: [main]
    
env:
  BUCKET: livvu
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Run tests
        run: yarn test --watchAll false
        
      - name: Build
        run: yarn build
        
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Upload files to bucket
        run: gsutil -m rsync -R ./build gs://"$BUCKET"
        
      - name: Allow AllUsers
        run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"

      - name: Set Cache-Control
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=1576800" gs://"$BUCKET"/**/*.{png,svg,css,js}
        
      - name: Set Cache-Control
        run: gsutil -m setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
